resources:
- name: postgres-release-develop
  type: git
  source:
    uri: https://github.com/cloudfoundry/postgres-release.git
    branch: develop

jobs:
- name: run-acceptance-tests
  serial_groups: [pgats]
  plan:
  - in_parallel:
    - get: postgres-release
      resource: postgres-release-develop
      trigger: true
  - task: create-postgres-dev-release-tarball
    file: postgres-release/ci/scripts/create-dev-release-tarball/task.yml
    input_mapping: {dev-release: postgres-release}
    output_mapping: {dev-release-tarball: postgres-tarball}
    params: &bosh2_params
      BOSH_DIRECTOR_IP: {{bosh2_director}}
      BOSH_DIRECTOR_NAME: {{bosh2_director_name}}
      BOSH_CLIENT: {{bosh2_user}}
      BOSH_CLIENT_SECRET: {{bosh2_password}}
      BOSH_CA_CERT: {{bosh2_ca_cert}}
      REL_NAME: postgres
      REL_VERSION: v99+dev.1
      BBR_VERSION: 1.3.2
      STEMCELL_VERSION: {{stemcell_version}}
      STEMCELL_TYPE: bosh-softlayer-xen-ubuntu-xenial
  - task: upload-postgres-dev-release
    file: postgres-release/ci/scripts/upload-dev-release-tarball/task.yml
    input_mapping: {dev-release-tarball: postgres-tarball}
    params:
      <<: *bosh2_params
  - task: upload-stemcell
    file: postgres-release/ci/scripts/upload-stemcell/task.yml
    params:
      <<: *bosh2_params
  - task: run-acceptance-tests
    file: postgres-release/ci/scripts/run-acceptance-tests/task.yml
    params:
      <<: *bosh2_params
    ensure:
      task: delete-postgres-dev-release
      file: postgres-release/ci/scripts/run-bosh-delete-release/task.yml
      params:
        <<: *bosh2_params
