resources:
- name: postgres-release
  type: git
  source:
    uri: https://github.com/cloudfoundry/postgres-release.git
    branch: develop

jobs:
- name: delete-cf-deployment
  serial_groups: [cleanup]
  plan:
  - in_parallel:
    - get: postgres-release
      resource: postgres-release
  - task: delete-cf-deployment
    file: postgres-release/ci/scripts/run-bosh-delete/task.yml
    params: &lite_params
      BOSH_DIRECTOR_IP: {{lite_bosh_director}}
      BOSH_DIRECTOR_NAME: {{lite_bosh_director_name}}
      BOSH_CLIENT: {{lite_bosh_user}}
      BOSH_CLIENT_SECRET: {{lite_bosh_password}}
      BOSH_CA_CERT: {{lite_bosh_ca_cert}}

- name: cleanup-resources
  serial_groups: [cleanup]
  plan:
  - in_parallel:
    - get: postgres-release
      resource: postgres-release
      passed: [delete-cf-deployment]
      trigger: true
  - task: cleanup-releases
    file: postgres-release/ci/scripts/run-bosh-cleanup/task.yml
    params:
      <<: *lite_params
