resources:
- name: postgres-release-develop
  type: git
  source:
    uri: https://github.com/cloudfoundry/postgres-release.git
    branch: develop
    disable_ci_skip: true

- name: oss-s3-buckets-stack
  type: git
  source:
    branch: master
    private_key: {{oss-s3-buckets-stack-private-key}}
    uri: git@github.com:cloudfoundry/oss-s3-buckets-stack.git

- name: postgres-release-master
  type: git
  source:
    uri: git@github.com:cloudfoundry/postgres-release.git
    branch: master
    private_key: {{postgres-release-private-key}}
    disable_ci_skip: true

- name: postgres-release-merge-target
  type: git
  source:
    uri: git@github.com:cloudfoundry/postgres-release.git
    branch: develop
    private_key: {{postgres-release-private-key}}
    disable_ci_skip: true

jobs:
- name: create-final-release
  serial_groups: [promote]
  plan:
  - aggregate:
    - get: oss-s3-buckets-stack
      resource: oss-s3-buckets-stack
    - get: release-repo
      resource: postgres-release-develop
    - get: release-repo-master
      resource: postgres-release-master
  - task: create-final-release
    file: release-repo/ci/scripts/create-final-release/task.yml
    params:
      RELEASE_NAME: postgres
  - put: postgres-release-master
    params:
      repository: final-release-repo
      tag: final-release-repo/version_number
      tag_prefix: v

- name: merge-master-into-develop
  serial_groups: [promote]
  plan:
  - aggregate:
    - get: postgres-release
      resource: postgres-release-develop
    - get: release-repo-master
      resource: postgres-release-master
      trigger: true
    - get: release-repo
      resource: postgres-release-merge-target
  - task: merge-master-into-develop
    file: postgres-release/ci/scripts/merge-master-into-develop/task.yml
  - put: postgres-release-merge-target
    params:
      repository: final-release-repo
